### ISSUE TITLE
Caching breaks the action

### ISSUE THREAD

**Issue by simo5** [vapier/coverity-scan-action#5]
When caching works the cov-analysis directory is recreated by the cache action.
This makes the subsequent mkdir fail, and the job fails:

See here for example: https://github.com/simo5/gssproxy/runs/7521485529
```
Run mkdir cov-analysis
  mkdir cov-analysis
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    RUN_COV: 1
mkdir: cannot create directory ‘cov-analysis’: File exists
```

It may be sufficient to call mkdir -p cov-analysis instead

**Comment by vapier** [comment]
pretty sure the problem is that you haven't configured your project correctly.  you can see in the output that the hash key is not set which implies the curl command failed with access denied.

i improved this flow already to fail earlier but didn't tag it.  let me update the v1 tag and you can rerun to see it fail sooner.

**Comment by simo5** [comment]
Yeah this was a run on the personal tree where I had already remove the secrets.
Odd that it passes through the first step though.
That said I cannot see where in the output I would see this, I tried to debug this action while setting up the project and I could never figure out why it was failing.
